site_name: Binu Pradeep
site_url: https://github.com/binuengoor/binupradeep-mkdocs
site_author: Binu Pradeep
site_description: >-
  Personal blog and portfolio of Binu Pradeep. 
  I also write about technology, programming, and other things that interest me.

theme:
  name: material
  palette: 
    - scheme: slate
      primary: black
      accent: deep orange

  font:
    text: Roboto
    code: Roboto Mono

  language: en

  logo: assets/logo.svg
  favicon: assets/favicon.ico

  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra_css:
  - stylesheets/extra.css

plugins:
  - awesome-pages
  - blog:
      blog_dir: blog
      authors: false
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
  - resize-images:
      source-dir: assets-large
      target-dir: assets
      size: [800, 600]
      extensions: ['.jpg', '.jpeg', '.png', '.gif', '.svg']
  - search:
      lang: 'en'
  - social
  - tags:
      tags_file: tags.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/binuepradeep/
    - icon: fontawesome/brands/github-alt
      link: https://github.com/binuengoor
    - icon: material/email-edit
      link: mailto:contact@binupradeep.com

copyright: Copyright &copy; Binu Pradeep 2024 -

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - tables
  - toc:
      title: On This Page
      permalink: true
      toc_depth: '3'
      separator: '-'
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # Copyright
