site_name: Binu Pradeep
site_url: https://github.com/binuengoor/binupradeep-mkdocs
site_author: Binu Pradeep
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable, in 60+ languages, for all devices

theme:
  name: material

  palette: 
    - scheme: slate
      primary: black
      accent: amber

  font:
    text: Roboto
    code: Roboto Mono

  language: en

  logo: assets/logo.svg
  favicon: assets/favicon.ico

  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
  - blog:
      authors: false
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
  - search:
      lang: 'en'
  - social
  - tags:
      tags_file: tags.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/binuepradeep/
    - icon: fontawesome/brands/github-alt
      link: https://github.com/binuengoor
    - icon: material/email-edit
      link: mailto:contact@binupradeep.com

copyright: Copyright &copy; Binu Pradeep 2024 -